spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 765147924254-26hkmmjumep9ffpdc0cvfm06unihn7l6.apps.googleusercontent.com
            client-secret: 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
    user:
      name: admin
      password: 143b2947-1bf9-4de6-ac8c-5086221acfb8
  datasource:
    url: jdbc:postgresql://localhost:8011/pipocaagil
    username: pipocaagil
    password: pipocaagil
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migration: true
server:
  port: 8080
jwt:
  secret: 977ae362-9ac5-4b2e-8a7d-07f7b7ca42e6
  expiration: 3600