spring:
  security:
    user:
      name: admin
      password: 143b2947-1bf9-4de6-ac8c-5086221acfb8
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migration: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600