spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mateuscristofori@gmail.com
    password: fwimmiwgwwnegrwl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 765147924254-jqv67va2oiq8uqp075n92anqgm4r8a8m.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/logingoogle/oauth2/code/google"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://accounts.google.com/o/oauth2/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: name
  datasource:
    url: jdbc:postgresql://localhost:8011/pipocaagil
    username: pipocaagil
    password: pipocaagil
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migration: true
server:
  port: 8080
jwt:
  expiration: 100000
