spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/logingoogle/oauth2/code/google"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://accounts.google.com/o/oauth2/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: name
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migration: true
server:
  port: 8080
jwt:
  expiration: ${JWT_EXPIRATION}

