CREATE TABLE users (
  id SERIAL PRIMARY KEY UNIQUE,
  role VARCHAR(40) NOT NULL,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(60) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  date_birth DATE NOT NULL
);